module.exports = {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#c6c6c6',
        'error-container': '#ffdad6',
        'on-tertiary-fixed': '#ffffff',
        'secondary-fixed-dim': '#acabab',
        'surface-container-highest': '#e8e2cf',
        'on-primary': '#e2e2e2',
        'surface-bright': '#fff9e8',
        'primary-container': '#3b3b3b',
        'primary-fixed': '#5e5e5e',
        'inverse-on-surface': '#f7f1dc',
        'on-surface-variant': '#474747',
        'on-secondary-fixed-variant': '#3b3b3b',
        outline: '#777777',
        'on-surface': '#1e1c10',
        'on-tertiary-container': '#ffffff',
        'on-secondary-fixed': '#1b1c1c',
        'surface-dim': '#e0dac6',
        'tertiary-fixed-dim': '#005321',
        'on-secondary-container': '#1b1c1c',
        'on-primary-fixed': '#ffffff',
        'inverse-surface': '#333123',
        surface: '#fff9e8',
        'surface-container-lowest': '#ffffff',
        'secondary-container': '#d6d4d4',
        secondary: '#5e5e5e',
        'on-tertiary': '#6bff8f',
        'secondary-fixed': '#c8c6c6',
        error: '#ba1a1a',
        'on-background': '#1e1c10',
        'on-secondary': '#ffffff',
        'surface-container-high': '#eee8d4',
        'tertiary-fixed': '#006e2f',
        'on-tertiary-fixed-variant': '#6bff8f',
        'on-primary-fixed-variant': '#e2e2e2',
        'surface-variant': '#e8e2cf',
        'surface-tint': '#5e5e5e',
        'surface-container': '#f4eeda',
        'primary-fixed-dim': '#474747',
        'on-primary-container': '#ffffff',
        tertiary: '#00461b',
        primary: '#000000',
        'outline-variant': '#c6c6c6',
        'on-error': '#ffffff',
        background: '#fff9e8',
        'tertiary-container': '#00873b',
        'surface-container-low': '#faf4df',
        'on-error-container': '#410002',
      },
      borderRadius: {
        none: "0px",
        DEFAULT: "0px",
        lg: "0px",
        xl: "0.75rem",
        full: "9999px"
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Space Grotesk", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"]
      },
      boxShadow: {
        hard: "8px 8px 0px 0px rgba(0,0,0,1)",
        block: "4px 4px 0px 0px rgba(0,0,0,1)",
        focus: "0 0 0 2px #000000"
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
